'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Image from 'next/image'
import { CheckCircle, XCircle, Stethoscope, Calendar } from 'lucide-react'

interface VerifyResult {
  valid: boolean
  prescriptionId?: string
  consultationId?: string
  date?: string
  doctor?: string
  qualification?: string
  specialisation?: string
}

export default function VerifyPage() {
  const { id } = useParams<{ id: string }>()
  const [result, setResult] = useState<VerifyResult | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch(`/api/verify/${encodeURIComponent(id)}`)
      .then(r => r.json())
      .then(setResult)
      .catch(() => setResult({ valid: false }))
      .finally(() => setLoading(false))
  }, [id])

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center px-4 py-12">
      <div className="w-full max-w-md">
        {/* Logo */}
        <div className="flex justify-center mb-8">
          <Image src="/images/neo-logo.png" alt="NeoFuture" width={180} height={55} className="object-contain" />
        </div>

        {loading ? (
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 text-center">
            <div className="w-12 h-12 border-4 border-orange-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
            <p className="text-gray-500 text-sm">Verifying prescription…</p>
          </div>
        ) : result?.valid ? (
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            {/* Green verified bar */}
            <div className="bg-[#fa4505] px-6 py-5 text-white text-center">
              <CheckCircle size={40} className="mx-auto mb-2" />
              <h1 className="text-lg font-bold">Prescription Verified</h1>
              <p className="text-sm opacity-85 mt-1">This is an authentic NeoFuture prescription</p>
            </div>

            <div className="p-6 space-y-4">
              <Row label="Prescription ID" value={result.prescriptionId!} />
              <Row label="Consultation ID" value={result.consultationId!} />
              <Row label="Issued On" value={result.date!} icon={<Calendar size={14} className="text-[#fa4505]" />} />
              <Row label="Prescribing Doctor" value={`${result.doctor} — ${result.qualification} · ${result.specialisation}`} icon={<Stethoscope size={14} className="text-[#fa4505]" />} />
            </div>

            <div className="bg-gray-50 px-6 py-3 text-center">
              <p className="text-xs text-gray-400">Generated by NeoFuture Wellness · neofuture.in</p>
            </div>
          </div>
        ) : (
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 text-center">
            <XCircle size={48} className="mx-auto text-red-400 mb-4" />
            <h1 className="text-lg font-bold text-gray-800 mb-1">Prescription Not Found</h1>
            <p className="text-sm text-gray-500">This prescription ID could not be verified. It may be invalid or not issued through NeoFuture.</p>
          </div>
        )}
      </div>
    </div>
  )
}

function Row({ label, value, icon }: { label: string; value: string; icon?: React.ReactNode }) {
  return (
    <div className="flex items-start gap-3">
      <div className="mt-0.5">{icon ?? <div className="w-3.5 h-3.5" />}</div>
      <div>
        <p className="text-xs text-gray-400 font-medium">{label}</p>
        <p className="text-sm text-gray-800 font-semibold">{value}</p>
      </div>
    </div>
  )
}
